# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 835)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.openDirButton.setGeometry(QtCore.QRect(610, 650, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.openDirButton.setFont(font)
        self.openDirButton.setObjectName("openDirButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(390, 650, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.simpleClickButton = QtWidgets.QPushButton(self.centralwidget)
        self.simpleClickButton.setGeometry(QtCore.QRect(450, 130, 141, 41))
        self.simpleClickButton.setObjectName("simpleClickButton")
        self.keyPressButton = QtWidgets.QPushButton(self.centralwidget)
        self.keyPressButton.setGeometry(QtCore.QRect(450, 190, 141, 41))
        self.keyPressButton.setObjectName("keyPressButton")
        self.clickIfPictureButton = QtWidgets.QPushButton(self.centralwidget)
        self.clickIfPictureButton.setGeometry(QtCore.QRect(450, 310, 141, 41))
        self.clickIfPictureButton.setObjectName("clickIfPictureButton")
        self.clickOnPictureButton = QtWidgets.QPushButton(self.centralwidget)
        self.clickOnPictureButton.setGeometry(QtCore.QRect(450, 380, 141, 41))
        self.clickOnPictureButton.setObjectName("clickOnPictureButton")
        self.locateRessourceButton = QtWidgets.QPushButton(self.centralwidget)
        self.locateRessourceButton.setGeometry(QtCore.QRect(450, 450, 141, 41))
        self.locateRessourceButton.setObjectName("locateRessourceButton")
        self.pictureWidget = QtWidgets.QListWidget(self.centralwidget)
        self.pictureWidget.setGeometry(QtCore.QRect(600, 250, 231, 301))
        self.pictureWidget.setObjectName("pictureWidget")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(660, 560, 93, 28))
        self.addButton.setObjectName("addButton")
        self.deleteLastButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteLastButton.setGeometry(QtCore.QRect(400, 560, 161, 61))
        self.deleteLastButton.setObjectName("deleteLastButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 20, 351, 711))
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 709))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(349, 709))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textlist = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.textlist.setGeometry(QtCore.QRect(0, 0, 351, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textlist.sizePolicy().hasHeightForWidth())
        self.textlist.setSizePolicy(sizePolicy)
        self.textlist.setMouseTracking(False)
        self.textlist.setText("")
        self.textlist.setScaledContents(False)
        self.textlist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.textlist.setWordWrap(True)
        self.textlist.setObjectName("textlist")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.openConfigButton = QtWidgets.QPushButton(self.centralwidget)
        self.openConfigButton.setGeometry(QtCore.QRect(610, 700, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.openConfigButton.setFont(font)
        self.openConfigButton.setObjectName("openConfigButton")
        self.xLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.xLabel.setGeometry(QtCore.QRect(630, 140, 51, 22))
        self.xLabel.setObjectName("xLabel")
        self.yLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.yLabel.setGeometry(QtCore.QRect(710, 140, 51, 22))
        self.yLabel.setObjectName("yLabel")
        self.timeLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(630, 200, 101, 22))
        self.timeLabel.setObjectName("timeLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setTearOffEnabled(False)
        self.menuSettings.setSeparatorsCollapsible(False)
        self.menuSettings.setToolTipsVisible(False)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.openDirButton.clicked.connect(MainWindow.openDir)
        self.actionOpen.triggered.connect(MainWindow.openDir)
        self.saveButton.clicked.connect(MainWindow.save)
        self.simpleClickButton.clicked.connect(MainWindow.simpleClick)
        self.clickOnPictureButton.clicked.connect(MainWindow.clickOnPicture)
        self.keyPressButton.clicked.connect(MainWindow.keyPress)
        self.clickIfPictureButton.clicked.connect(MainWindow.clickIfPicture)
        self.locateRessourceButton.clicked.connect(MainWindow.locateRessource)
        self.addButton.clicked.connect(MainWindow.add)
        self.deleteLastButton.clicked.connect(MainWindow.deleteLast)
        self.openConfigButton.clicked.connect(MainWindow.openConfig)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openDirButton.setText(_translate("MainWindow", "Open Folder"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.simpleClickButton.setText(_translate("MainWindow", "Simple Click"))
        self.keyPressButton.setText(_translate("MainWindow", "Key Press"))
        self.clickIfPictureButton.setText(_translate("MainWindow", "Click if Picture"))
        self.clickOnPictureButton.setText(_translate("MainWindow", "click On Picture"))
        self.locateRessourceButton.setText(_translate("MainWindow", "locate Ressource"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.deleteLastButton.setText(_translate("MainWindow", "Delete Last"))
        self.openConfigButton.setText(_translate("MainWindow", "Open Config"))
        self.xLabel.setInputMask(_translate("MainWindow", "9999"))
        self.xLabel.setPlaceholderText(_translate("MainWindow", "X"))
        self.yLabel.setInputMask(_translate("MainWindow", "9999"))
        self.yLabel.setPlaceholderText(_translate("MainWindow", "Y"))
        self.timeLabel.setInputMask(_translate("MainWindow", "9999"))
        self.timeLabel.setPlaceholderText(_translate("MainWindow", "time in s"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

