# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 874)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-1, -1, 850, 841))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.play_tab = QtWidgets.QWidget()
        self.play_tab.setObjectName("play_tab")
        self.loadGame = QtWidgets.QPushButton(self.play_tab)
        self.loadGame.setGeometry(QtCore.QRect(30, 40, 141, 41))
        self.loadGame.setObjectName("loadGame")
        self.topLeft = QtWidgets.QPushButton(self.play_tab)
        self.topLeft.setGeometry(QtCore.QRect(30, 120, 141, 41))
        self.topLeft.setObjectName("topLeft")
        self.bottomRight = QtWidgets.QPushButton(self.play_tab)
        self.bottomRight.setGeometry(QtCore.QRect(180, 120, 141, 41))
        self.bottomRight.setObjectName("bottomRight")
        self.start_stop = QtWidgets.QPushButton(self.play_tab)
        self.start_stop.setGeometry(QtCore.QRect(30, 190, 141, 41))
        self.start_stop.setObjectName("start_stop")
        self.tabWidget.addTab(self.play_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.gameplay_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameplay_tab.sizePolicy().hasHeightForWidth())
        self.gameplay_tab.setSizePolicy(sizePolicy)
        self.gameplay_tab.setObjectName("gameplay_tab")
        self.clickIfPictureButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.clickIfPictureButton.setGeometry(QtCore.QRect(440, 278, 141, 41))
        self.clickIfPictureButton.setObjectName("clickIfPictureButton")
        self.addButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.addButton.setGeometry(QtCore.QRect(650, 528, 93, 28))
        self.addButton.setObjectName("addButton")
        self.keyPressButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.keyPressButton.setGeometry(QtCore.QRect(440, 158, 141, 41))
        self.keyPressButton.setObjectName("keyPressButton")
        self.locateRessourceButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.locateRessourceButton.setGeometry(QtCore.QRect(440, 418, 141, 41))
        self.locateRessourceButton.setObjectName("locateRessourceButton")
        self.scrollArea = QtWidgets.QScrollArea(self.gameplay_tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 351, 711))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 709))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(349, 709))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textlist = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.textlist.setGeometry(QtCore.QRect(0, 0, 351, 710))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textlist.sizePolicy().hasHeightForWidth())
        self.textlist.setSizePolicy(sizePolicy)
        self.textlist.setMouseTracking(False)
        self.textlist.setText("")
        self.textlist.setScaledContents(False)
        self.textlist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.textlist.setWordWrap(True)
        self.textlist.setObjectName("textlist")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.yLabel = QtWidgets.QLineEdit(self.gameplay_tab)
        self.yLabel.setGeometry(QtCore.QRect(700, 108, 71, 22))
        self.yLabel.setObjectName("yLabel")
        self.xLabel = QtWidgets.QLineEdit(self.gameplay_tab)
        self.xLabel.setGeometry(QtCore.QRect(620, 108, 71, 22))
        self.xLabel.setObjectName("xLabel")
        self.keyLabel = QtWidgets.QLineEdit(self.gameplay_tab)
        self.keyLabel.setGeometry(QtCore.QRect(620, 168, 101, 22))
        self.keyLabel.setInputMask("")
        self.keyLabel.setText("")
        self.keyLabel.setObjectName("keyLabel")
        self.openDirButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.openDirButton.setGeometry(QtCore.QRect(600, 618, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.openDirButton.setFont(font)
        self.openDirButton.setObjectName("openDirButton")
        self.pictureWidget = QtWidgets.QListWidget(self.gameplay_tab)
        self.pictureWidget.setGeometry(QtCore.QRect(590, 218, 231, 301))
        self.pictureWidget.setObjectName("pictureWidget")
        self.simpleClickButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.simpleClickButton.setGeometry(QtCore.QRect(440, 98, 141, 41))
        self.simpleClickButton.setObjectName("simpleClickButton")
        self.saveButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.saveButton.setGeometry(QtCore.QRect(380, 618, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.clickOnPictureButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.clickOnPictureButton.setGeometry(QtCore.QRect(440, 348, 141, 41))
        self.clickOnPictureButton.setObjectName("clickOnPictureButton")
        self.openConfigButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.openConfigButton.setGeometry(QtCore.QRect(600, 668, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.openConfigButton.setFont(font)
        self.openConfigButton.setObjectName("openConfigButton")
        self.deleteLastButton = QtWidgets.QPushButton(self.gameplay_tab)
        self.deleteLastButton.setGeometry(QtCore.QRect(390, 528, 161, 61))
        self.deleteLastButton.setObjectName("deleteLastButton")
        self.tabWidget.addTab(self.gameplay_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setTearOffEnabled(False)
        self.menuSettings.setSeparatorsCollapsible(False)
        self.menuSettings.setToolTipsVisible(False)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionOpen.triggered.connect(MainWindow.openDir)
        self.addButton.clicked.connect(MainWindow.add)
        self.clickIfPictureButton.clicked.connect(MainWindow.clickIfPicture)
        self.clickOnPictureButton.clicked.connect(MainWindow.clickOnPicture)
        self.deleteLastButton.clicked.connect(MainWindow.deleteLast)
        self.keyPressButton.clicked.connect(MainWindow.keyPress)
        self.locateRessourceButton.clicked.connect(MainWindow.locateRessource)
        self.openConfigButton.clicked.connect(MainWindow.openConfig)
        self.openDirButton.clicked.connect(MainWindow.openDir)
        self.saveButton.clicked.connect(MainWindow.save)
        self.simpleClickButton.clicked.connect(MainWindow.simpleClick)
        self.loadGame.clicked.connect(MainWindow.loadGame)
        self.topLeft.clicked.connect(MainWindow.selectTopLeft)
        self.start_stop.clicked.connect(MainWindow.start_stop)
        self.bottomRight.clicked.connect(MainWindow.selectBottomRight)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadGame.setText(_translate("MainWindow", "Load Game"))
        self.topLeft.setText(_translate("MainWindow", "Top Left"))
        self.bottomRight.setText(_translate("MainWindow", "Bottom Right"))
        self.start_stop.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.play_tab), _translate("MainWindow", "Play"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Create"))
        self.clickIfPictureButton.setText(_translate("MainWindow", "Click if Picture"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.keyPressButton.setText(_translate("MainWindow", "Key Press"))
        self.locateRessourceButton.setText(_translate("MainWindow", "locate Ressource"))
        self.yLabel.setInputMask(_translate("MainWindow", "9999"))
        self.yLabel.setPlaceholderText(_translate("MainWindow", "Y"))
        self.xLabel.setInputMask(_translate("MainWindow", "9999"))
        self.xLabel.setPlaceholderText(_translate("MainWindow", "X"))
        self.keyLabel.setPlaceholderText(_translate("MainWindow", "Press Key"))
        self.openDirButton.setText(_translate("MainWindow", "Open Folder"))
        self.simpleClickButton.setText(_translate("MainWindow", "Simple Click"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.clickOnPictureButton.setText(_translate("MainWindow", "click On Picture"))
        self.openConfigButton.setText(_translate("MainWindow", "Open Config"))
        self.deleteLastButton.setText(_translate("MainWindow", "Delete Last"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gameplay_tab), _translate("MainWindow", "Gameplay"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

